apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-03-21T21:23:59Z
  generation: 1
  labels:
    run: kubernetes-william
  name: kubernetes-william
  namespace: default
  resourceVersion: "9106"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/kubernetes-william
  uid: a43564fd-4c1f-11e9-a157-42010aa400a7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: kubernetes-william
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kubernetes-william
    spec:
      containers:
      - image: gcr.io/kubernetes-william/kubernetes-workshop:d317e9af66f5e39901b1ba2c5733b149d848113b
        imagePullPolicy: IfNotPresent
        name: kubernetes-william
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-03-21T21:24:35Z
    lastUpdateTime: 2019-03-21T21:24:35Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-03-21T21:23:59Z
    lastUpdateTime: 2019-03-21T21:24:35Z
    message: ReplicaSet "kubernetes-william-cf4bfd4fb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
