apiVersion: v1
kind: Service
metadata:
  labels:
    run: kubernetes-william
  name: kubernetes-william
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32475
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: kubernetes-william
  sessionAffinity: None
  type: LoadBalancer
